### PR TITLE
Fix error found by PHPCS

### PR DESCRIPTION
**Pull request by kizule**

### CODE REVIEW

**Comment by kizule** [comment]
After fix:
```zoranzoki21@srwiki-dev:/tmp/ProtectionIndicator$ composer test
> parallel-lint . --exclude vendor --exclude node_modules
PHP 7.3.11 | 10 parallel jobs
...                                                          3/3 (100 %)


Checked 3 files in 0 seconds
No syntax error found
> phpcs -p -s
...... 6 / 6 (100%)


Time: 91ms; Memory: 8MB

> minus-x check .
MinusX
======
Processing /tmp/ProtectionIndicator...
....................
All good!
zoranzoki21@srwiki-dev:/tmp/ProtectionIndicator$
```

**Comment by sohomdatta1** [comment]
Sure, thanks for catching that :)

**Comment by sohomdatta1** [comment]
Shit, GitHub confused me :)

**Comment by kizule** [comment]
No problem :) Thanks for merging!

**Pull request merged**
